name: fitness_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  intl: ^0.17.0
  provider: ^6.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/icon/
    - lib/images/
    - lib/exercises/
  fonts:
    - family: TTNormsPro
      fonts:
        - asset: lib/fonts/TTNormsProBold.otf
        - asset: lib/fonts/TTNormsProMedium.otf
